#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: dol [sphinx|gatling] [command...]"
    exit
fi

PWD=`pwd`

if [ $WINDIR != "" ]; then
    WINPWD=`echo $PWD | sed 's|/[Cc]|c:|'`
    WINPTY=winpty
fi

function check_build() {
    check=`docker images -q $1`
    if [ "$check" = "" ]; then
        echo $2
        eval $2
    fi
}

case $1 in
sphinx)
    shift
    check_build sphinx "docker build -t sphinx ./sphinx"
    if [ $# -eq 0 ]; then
        echo "dol sphinx build - build docker image form Dockerfile."
        echo "           html  - build sphinx docs."
        echo "           clean - clean build dir."
        echo "           *     - run sphninx command."
        echo "at $WINPWD"
        exit
    fi
    case $1 in
    html)
        echo docker run -tv $WINPWD:/work --rm sphinx make html
        docker run -tv $WINPWD:/work --rm sphinx make html
        ;;
    clean)
        echo docker run -tv $WINPWD:/work --rm sphinx make clean
        docker run -tv $WINPWD:/work --rm sphinx make clean
        ;;
    make)
        echo docker run -tv $WINPWD:/work --rm sphinx $*
        docker run -tv $WINPWD:/work --rm sphinx $*
        ;;
    esac
    ;;

gatling)
    shift
    check_build denvazh/gatling "docker pull denvazh/gatling:latest"
    if [ $# -eq 0 ]; then
        echo "dol gatling build"
        echo "            run"
        echo "            clean"
        exit
    fi
    case $1 in
    run)
        echo docker run -t --rm -v $WINPWD/conf:/opt/gatling/conf \
            -v $WINPWD/user-files:/opt/gatling/user-files \
            -v $WINPWD/results:/opt/gatling/results \
            denvazh/gatling
        docker run -t --rm -v $WINPWD/conf:/opt/gatling/conf \
            -v $WINPWD/user-files:/opt/gatling/user-files \
            -v $WINPWD/results:/opt/gatling/results \
            denvazh/gatling
        ;;
    clean)
        rm -fr $WINPWD/results/*
        ;;
    esac
    ;;
esac
