#!/bin/sh
# dos is docker on script.

# usage
if [ $# -eq 0 ]; then
    echo "Usage: dos [sphinx|gatling] [command...]"
    exit
fi

PWD=`pwd`

# docker is strange...
WINPWD=`echo $PWD | sed 's|/[Cc]|c:|'`
WINPTY=winpty

# 1st command
case $1 in
sphinx)
    shift
    if [ $# -eq 0 ]; then
        echo "dos sphinx build      - build docker image form Dockerfile."
        echo "           make html  - build sphinx docs."
        echo "           make clean - clean build dir."
        echo "at $WINPWD"
        exit
    fi
    case $1 in
    build)
        echo docker build -t sphinx ./sphinx
        docker build -t sphinx ./sphinx
        ;;
    make)
        echo docker run -tv $WINPWD:/work --rm sphinx $*
        docker run -tv $WINPWD:/work --rm sphinx $*
        ;;
    esac
    ;;

gatling)
    shift
    if [ $# -eq 0 ]; then
        echo "dos gatling build"
        echo "            run"
        echo "            clean"
        exit
    fi
    case $1 in
    build)
        echo docker pull denvazh/gatling:latest
        docker pull denvazh/gatling:latest
        ;;
    run)
        echo docker run -t --rm -v $WINPWD/conf:/opt/gatling/conf \
            -v $WINPWD/user-files:/opt/gatling/user-files \
            -v $WINPWD/results:/opt/gatling/results \
            denvazh/gatling
        docker run -t --rm -v $WINPWD/conf:/opt/gatling/conf \
            -v $WINPWD/user-files:/opt/gatling/user-files \
            -v $WINPWD/results:/opt/gatling/results \
            denvazh/gatling
        ;;
    clean)
        rm -fr $WINPWD/results/*
        ;;
    esac
    ;;
esac
